name: Open Telemetry CI/CD Action
description: Export CI/CD workflows to any endpoint compatible with OpenTelemetry
author: Corentin Musard

runs:
  using: node20
  main: dist/index.js

inputs:
  otlpEndpoint:
    description: The destination endpoint to export OpenTelemetry traces to
    required: true
  otlpHeaders:
    description: Network Headers for the destination endpoint to export OpenTelemetry traces to
    required: true
  otelServiceName:
    description: OpenTelemetry service name
    required: false
    default: ""
  githubToken:
    description: The repository token with Workflow permissions. i.e. secrets.GITHUB_TOKEN
    required: false
  runId:
    description: Workflow Run ID to Export. Defaults to env.GITHUB_RUN_ID
    required: false
  extraAttributes:
    description: Extra resource attributes to add to each span
    required: false
  parseLogParameters:
    description: Enable parsing span parameters from job logs
    required: false
    default: "true"
  spanParamsArtifact:
    description: Name of the artifact containing span parameters (created by emit-params action)
    required: false
    default: "otel-span-parameters"
outputs:
  traceId:
    description: The OpenTelemetry Trace ID of the root span

branding:
  icon: bar-chart-2
  color: green
